name: Atualizar Dashboard

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: atualizar-dashboard
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install psycopg2-binary pandas

      - name: Executar script de geração
        env:
          DB_HOST: ${{ aws-0-sa-east-1.pooler.supabase.com }}
          DB_PORT: ${{ 5432 }}
          DB_NAME: ${{ postgres }}
          DB_USER: ${{ analista_bi.cuofycgznnbtpotybpuu }}
          DB_PASSWORD: ${{ marvao#37m }}
        run: python gerar_dashboard.py

      - name: Fazer deploy para o GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
